### ISSUE TITLE
Server Side Render error

### ISSUE THREAD

**Issue by msimonc** [daixianceng/formik-material-fields#1]
Hi, thanks for this project!

FormikTextField works great in Development, 
but when I start my SSR Production server I get this error:

`(node:35556) UnhandledPromiseRejectionWarning: /Projects/cra-redux-feathers-ssr/cra-redux-feathers-ssr-client/node_modules/formik-material-fields/lib/index.js:1
(function (exports, require, module, __filename, __dirname) { export { default as CheckboxGroupField } from './CheckboxGroupField';
                                                              ^^^^^^

SyntaxError: Unexpected token export
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:617:28)
    at Module._compile (/Projects/cra-redux-feathers-ssr/cra-redux-feathers-ssr-client/node_modules/pirates/lib/index.js:83:24)
    at Module._extensions..js (module.js:664:10)
    at Object.newLoader [as .js] (/Projects/cra-redux-feathers-ssr/cra-redux-feathers-ssr-client/node_modules/pirates/lib/index.js:88:7)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Module.require (module.js:597:17)
(node:35556) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:35556) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

**Comment by daixianceng** [comment]
Thanks for your report. I fixed this issue with the version of `0.0.3`, please enter `npm i formik-material-fields` or `yarn add formik-material-fields` to upgrade.

**Comment by msimonc** [comment]
Thanks! from Sydney AU
